import Tkinter as Tk


class Application(Tk.Frame):
    def __init__(self, master=None):
        Tk.Frame.__init__(self, master)
        self.grid()
        self.create_widgets()

    def create_widgets(self):
        w = Tk.Label(self, text="Vs")
        w.grid(row=1, column=10, )
        f = Tk.Label(self, text="Vr")
        f.grid(row=3, column=10)
        g = Tk.Label(self, text="Vl")
        g.grid(row=5, column=10)
        h = Tk.Label(self, text="Vc")
        h.grid(row=7, column=10)
        e = Tk.Label(self, text="Xc")
        e.grid(row=9, column=10)
        i = Tk.Label(self, text="Xl")
        i.grid(row=11, column=10)
        a = Tk.Label(self, text="R")
        a.grid(row=1, column=17)
        b = Tk.Label(self, text="Z")
        b.grid(row=3, column=17)
        c = Tk.Label(self, text="f")
        c.grid(row=5, column=17)
        d = Tk.Label(self, text="C")
        d.grid(row=7, column=17)
        j = Tk.Label(self, text="L")
        j.grid(row=9, column=17)
        k = Tk.Label(self, text="θ")
        k.grid(row=11, column=17)

        m = Tk.Label(self, text="V")
        m.grid(row=1, column=12, )
        l = Tk.Label(self, text="V")
        l.grid(row=3, column=12)
        z = Tk.Label(self, text="V")
        z.grid(row=5, column=12)
        t = Tk.Label(self, text="V")
        t.grid(row=7, column=12)
        y = Tk.Label(self, text="Ω")
        y.grid(row=9, column=12)
        o = Tk.Label(self, text="Ω")
        o.grid(row=11, column=12)
        p = Tk.Label(self, text="Ω")
        p.grid(row=1, column=19)
        s = Tk.Label(self, text="Ω")
        s.grid(row=3, column=19)
        q = Tk.Label(self, text="Hz")
        q.grid(row=5, column=19)
        x = Tk.Label(self, text="H")
        x.grid(row=7, column=19)
        u = Tk.Label(self, text="F")
        u.grid(row=9, column=19)
        v = Tk.Label(self, text="°")
        v.grid(row=11, column=19)

        name = Tk.Entry(self)
        name.grid(row=1, column=11)
        name = Tk.Entry(self)
        name.grid(row=3, column=11)
        name = Tk.Entry(self)
        name.grid(row=5, column=11)
        name = Tk.Entry(self)
        name.grid(row=7, column=11)
        name = Tk.Entry(self)
        name.grid(row=9, column=11)
        name = Tk.Entry(self)
        name.grid(row=11, column=11)
        name = Tk.Entry(self)
        name.grid(row=1, column=18)
        name = Tk.Entry(self)
        name.grid(row=3, column=18)
        name = Tk.Entry(self)
        name.grid(row=5, column=18)
        name = Tk.Entry(self)
        name.grid(row=7, column=18)
        name = Tk.Entry(self)
        name.grid(row=9, column=18)
        name = Tk.Entry(self)
        name.grid(row=11, column=18)

        hello = Tk.Button(self, text="Calculator", )
        hello.grid(row=13, column=14)


app = Application()
app.master.title('Sample application')
app.mainloop()
